// Code generated by "stringer -type=Service localstack/services.go"; DO NOT EDIT.

package localstack

import "strconv"

const _Service_name = "S3SNSSQS"

var _Service_index = [...]uint8{0, 2, 5, 8}

func (i Service) String() string {
	i -= 1
	if i < 0 || i >= Service(len(_Service_index)-1) {
		return "Service(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Service_name[_Service_index[i]:_Service_index[i+1]]
}
