// Code generated by "stringer -type=Service localstack/services.go"; DO NOT EDIT.

package services

import "strconv"

const _Service_name = "APIGatewayKinesisDynamoDBDynamoDBStreamsS3FirehoseLambdaSNSSQSRedshiftESSESRoute53CloudFormationCloudWatchSSMSecretsManager"

var _Service_index = [...]uint8{0, 10, 17, 25, 40, 42, 50, 56, 59, 62, 70, 72, 75, 82, 96, 106, 109, 123}

func (i Service) String() string {
	i -= 1
	if i < 0 || i >= Service(len(_Service_index)-1) {
		return "Service(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Service_name[_Service_index[i]:_Service_index[i+1]]
}
